In [32]:
from pathlib import Path
import pandas as pd

data_dir = Path("../data")

In [33]:
csv_data = data_dir / 'data.csv'

In [34]:
df = pd.read_csv(csv_data)

In [35]:
df

,date,quarter,sp500,sp500cap,bist100,bist100cap,bistall,bistallcap,btc,eth,gold,rate,cpi,usdtry,eurtry
0,1964-03-31,1964Q1,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1964-04-01,1964Q2,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1964-04-02,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1964-04-03,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1964-04-06,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16075,2022-11-06,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"20,926","1,628",NaN,NaN,NaN,NaN,NaN
16076,2022-11-12,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,799","1,287",NaN,NaN,NaN,NaN,NaN
16077,2022-11-13,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,353","1,255",NaN,NaN,NaN,NaN,NaN
16078,2022-11-19,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,712","1,212",NaN,NaN,NaN,NaN,NaN
16079,2022-11-20,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,292","1,218",NaN,NaN,NaN,NaN,NaN

In [36]:
df.bist100.info

<bound method Series.info of 0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
16075    NaN
16076    NaN
16077    NaN
16078    NaN
16079    NaN
Name: bist100, Length: 16080, dtype: object>

In [37]:
def change_type(v: str | float):
    if isinstance(v, float):
        return v
    return v.strip('').strip(' ').replace(' ', '').strip().replace(',','.')

In [38]:
df.bist100 = df.bist100.apply(change_type)

In [39]:
df.bist100 = df.bist100.astype(float)

In [40]:
df

,date,quarter,sp500,sp500cap,bist100,bist100cap,bistall,bistallcap,btc,eth,gold,rate,cpi,usdtry,eurtry
0,1964-03-31,1964Q1,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1964-04-01,1964Q2,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1964-04-02,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1964-04-03,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1964-04-06,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16075,2022-11-06,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"20,926","1,628",NaN,NaN,NaN,NaN,NaN
16076,2022-11-12,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,799","1,287",NaN,NaN,NaN,NaN,NaN
16077,2022-11-13,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,353","1,255",NaN,NaN,NaN,NaN,NaN
16078,2022-11-19,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,712","1,212",NaN,NaN,NaN,NaN,NaN
16079,2022-11-20,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,292","1,218",NaN,NaN,NaN,NaN,NaN

In [41]:
df.set_index(df.date)

,date,quarter,sp500,sp500cap,bist100,bist100cap,bistall,bistallcap,btc,eth,gold,rate,cpi,usdtry,eurtry
date,,,,,,,,,,,,,,,
1964-03-31,1964-03-31,1964Q1,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-01,1964-04-01,1964Q2,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-02,1964-04-02,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-03,1964-04-03,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-06,1964-04-06,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-06,2022-11-06,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"20,926","1,628",NaN,NaN,NaN,NaN,NaN
2022-11-12,2022-11-12,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,799","1,287",NaN,NaN,NaN,NaN,NaN
2022-11-13,2022-11-13,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,353","1,255",NaN,NaN,NaN,NaN,NaN
2022-11-19,2022-11-19,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,712","1,212",NaN,NaN,NaN,NaN,NaN
2022-11-20,2022-11-20,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,292","1,218",NaN,NaN,NaN,NaN,NaN

In [42]:
df.index

RangeIndex(start=0, stop=16080, step=1)

In [43]:
df.index = pd.to_datetime(df.date)

In [44]:
df = df.drop_duplicates()

In [45]:
df

,date,quarter,sp500,sp500cap,bist100,bist100cap,bistall,bistallcap,btc,eth,gold,rate,cpi,usdtry,eurtry
date,,,,,,,,,,,,,,,
1964-03-31,1964-03-31,1964Q1,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-01,1964-04-01,1964Q2,79,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-02,1964-04-02,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-03,1964-04-03,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964-04-06,1964-04-06,1964Q2,80,"357,907",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-06,2022-11-06,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"20,926","1,628",NaN,NaN,NaN,NaN,NaN
2022-11-12,2022-11-12,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,799","1,287",NaN,NaN,NaN,NaN,NaN
2022-11-13,2022-11-13,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,353","1,255",NaN,NaN,NaN,NaN,NaN
2022-11-19,2022-11-19,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,712","1,212",NaN,NaN,NaN,NaN,NaN
2022-11-20,2022-11-20,2022Q4,NaN,NaN,NaN,NaN,NaN,NaN,"16,292","1,218",NaN,NaN,NaN,NaN,NaN

In [46]:
ror_daily = df.bist100.pct_change()

In [47]:
ror_daily

date
1964-03-31    NaN
1964-04-01    NaN
1964-04-02    NaN
1964-04-03    NaN
1964-04-06    NaN
             ...
2022-11-06    0.0
2022-11-12    0.0
2022-11-13    0.0
2022-11-19    0.0
2022-11-20    0.0
Name: bist100, Length: 16079, dtype: float64

In [48]:
ror_weekly = df.bist100.resample('W').ffill().pct_change()

In [49]:
ror_weekly

date
1964-04-05         NaN
1964-04-12         NaN
1964-04-19         NaN
1964-04-26         NaN
1964-05-03         NaN
                ...
2022-11-27    0.443293
2022-12-04    0.018260
2022-12-11    0.008463
2022-12-18    0.041758
2022-12-25    0.034139
Freq: W-SUN, Name: bist100, Length: 3065, dtype: float64

In [50]:
ror_monthly = df.bist100.resample('M').ffill().pct_change()

In [51]:
ror_monthly

date
1964-03-31         NaN
1964-04-30         NaN
1964-05-31         NaN
1964-06-30         NaN
1964-07-31         NaN
                ...
2022-08-31    0.223380
2022-09-30    0.002838
2022-10-31    0.251258
2022-11-30    0.251068
2022-12-31    0.083166
Freq: M, Name: bist100, Length: 706, dtype: float64

In [52]:
ror_bist100 = pd.DataFrame()

In [53]:
ror_bist100

Empty DataFrame
Columns: []
Index: []

In [54]:
ror_bist100['daily'] = ror_daily

In [55]:
ror_bist100

            daily
date
1964-03-31    NaN
1964-04-01    NaN
1964-04-02    NaN
1964-04-03    NaN
1964-04-06    NaN
...           ...
2022-11-06    0.0
2022-11-12    0.0
2022-11-13    0.0
2022-11-19    0.0
2022-11-20    0.0

[16079 rows x 1 columns]

In [56]:
ror_bist100['weekly'] = ror_weekly

In [57]:
ror_bist100

            daily  weekly
date
1964-03-31    NaN     NaN
1964-04-01    NaN     NaN
1964-04-02    NaN     NaN
1964-04-03    NaN     NaN
1964-04-06    NaN     NaN
...           ...     ...
2022-11-06    0.0     0.0
2022-11-12    0.0     NaN
2022-11-13    0.0     0.0
2022-11-19    0.0     NaN
2022-11-20    0.0     0.0

[16079 rows x 2 columns]

In [58]:
ror_weekly

date
1964-04-05         NaN
1964-04-12         NaN
1964-04-19         NaN
1964-04-26         NaN
1964-05-03         NaN
                ...
2022-11-27    0.443293
2022-12-04    0.018260
2022-12-11    0.008463
2022-12-18    0.041758
2022-12-25    0.034139
Freq: W-SUN, Name: bist100, Length: 3065, dtype: float64

In [59]:
ror_bist100['monthly'] = ror_monthly

In [60]:
ror_bist100

            daily  weekly  monthly
date
1964-03-31    NaN     NaN      NaN
1964-04-01    NaN     NaN      NaN
1964-04-02    NaN     NaN      NaN
1964-04-03    NaN     NaN      NaN
1964-04-06    NaN     NaN      NaN
...           ...     ...      ...
2022-11-06    0.0     0.0      NaN
2022-11-12    0.0     NaN      NaN
2022-11-13    0.0     0.0      NaN
2022-11-19    0.0     NaN      NaN
2022-11-20    0.0     0.0      NaN

[16079 rows x 3 columns]

In [61]:
period_1990_1999 = pd.date_range(start='1990-01-01', end='1999-12-31')

In [63]:
r1990_1999 = ror_bist100.loc[period_1990_1999, 'daily']

KeyError: "[Timestamp('1990-01-06 00:00:00'), Timestamp('1990-01-07 00:00:00'), Timestamp('1990-01-13 00:00:00'), Timestamp('1990-01-14 00:00:00'), Timestamp('1990-01-20 00:00:00'), Timestamp('1990-01-21 00:00:00'), Timestamp('1990-01-27 00:00:00'), Timestamp('1990-01-28 00:00:00'), Timestamp('1990-02-03 00:00:00'), Timestamp('1990-02-04 00:00:00'), Timestamp('1990-02-10 00:00:00'), Timestamp('1990-02-11 00:00:00'), Timestamp('1990-02-17 00:00:00'), Timestamp('1990-02-18 00:00:00'), Timestamp('1990-02-24 00:00:00'), Timestamp('1990-02-25 00:00:00'), Timestamp('1990-03-03 00:00:00'), Timestamp('1990-03-04 00:00:00'), Timestamp('1990-03-10 00:00:00'), Timestamp('1990-03-11 00:00:00'), Timestamp('1990-03-17 00:00:00'), Timestamp('1990-03-18 00:00:00'), Timestamp('1990-03-24 00:00:00'), Timestamp('1990-03-25 00:00:00'), Timestamp('1990-03-31 00:00:00'), Timestamp('1990-04-01 00:00:00'), Timestamp('1990-04-07 00:00:00'), Timestamp('1990-04-08 00:00:00'), Timestamp('1990-04-14 00:00:00'), Timestamp('1990-04-15 00:00:00'), Timestamp('1990-04-21 00:00:00'), Timestamp('1990-04-22 00:00:00'), Timestamp('1990-04-28 00:00:00'), Timestamp('1990-04-29 00:00:00'), Timestamp('1990-05-05 00:00:00'), Timestamp('1990-05-06 00:00:00'), Timestamp('1990-05-12 00:00:00'), Timestamp('1990-05-13 00:00:00'), Timestamp('1990-05-19 00:00:00'), Timestamp('1990-05-20 00:00:00'), Timestamp('1990-05-26 00:00:00'), Timestamp('1990-05-27 00:00:00'), Timestamp('1990-06-02 00:00:00'), Timestamp('1990-06-03 00:00:00'), Timestamp('1990-06-09 00:00:00'), Timestamp('1990-06-10 00:00:00'), Timestamp('1990-06-16 00:00:00'), Timestamp('1990-06-17 00:00:00'), Timestamp('1990-06-23 00:00:00'), Timestamp('1990-06-24 00:00:00'), Timestamp('1990-06-30 00:00:00'), Timestamp('1990-07-01 00:00:00'), Timestamp('1990-07-07 00:00:00'), Timestamp('1990-07-08 00:00:00'), Timestamp('1990-07-14 00:00:00'), Timestamp('1990-07-15 00:00:00'), Timestamp('1990-07-21 00:00:00'), Timestamp('1990-07-22 00:00:00'), Timestamp('1990-07-28 00:00:00'), Timestamp('1990-07-29 00:00:00'), Timestamp('1990-08-04 00:00:00'), Timestamp('1990-08-05 00:00:00'), Timestamp('1990-08-11 00:00:00'), Timestamp('1990-08-12 00:00:00'), Timestamp('1990-08-18 00:00:00'), Timestamp('1990-08-19 00:00:00'), Timestamp('1990-08-25 00:00:00'), Timestamp('1990-08-26 00:00:00'), Timestamp('1990-09-01 00:00:00'), Timestamp('1990-09-02 00:00:00'), Timestamp('1990-09-08 00:00:00'), Timestamp('1990-09-09 00:00:00'), Timestamp('1990-09-15 00:00:00'), Timestamp('1990-09-16 00:00:00'), Timestamp('1990-09-22 00:00:00'), Timestamp('1990-09-23 00:00:00'), Timestamp('1990-09-29 00:00:00'), Timestamp('1990-09-30 00:00:00'), Timestamp('1990-10-06 00:00:00'), Timestamp('1990-10-07 00:00:00'), Timestamp('1990-10-13 00:00:00'), Timestamp('1990-10-14 00:00:00'), Timestamp('1990-10-20 00:00:00'), Timestamp('1990-10-21 00:00:00'), Timestamp('1990-10-27 00:00:00'), Timestamp('1990-10-28 00:00:00'), Timestamp('1990-11-03 00:00:00'), Timestamp('1990-11-04 00:00:00'), Timestamp('1990-11-10 00:00:00'), Timestamp('1990-11-11 00:00:00'), Timestamp('1990-11-17 00:00:00'), Timestamp('1990-11-18 00:00:00'), Timestamp('1990-11-24 00:00:00'), Timestamp('1990-11-25 00:00:00'), Timestamp('1990-12-01 00:00:00'), Timestamp('1990-12-02 00:00:00'), Timestamp('1990-12-08 00:00:00'), Timestamp('1990-12-09 00:00:00'), Timestamp('1990-12-15 00:00:00'), Timestamp('1990-12-16 00:00:00'), Timestamp('1990-12-22 00:00:00'), Timestamp('1990-12-23 00:00:00'), Timestamp('1990-12-29 00:00:00'), Timestamp('1990-12-30 00:00:00'), Timestamp('1991-01-05 00:00:00'), Timestamp('1991-01-06 00:00:00'), Timestamp('1991-01-12 00:00:00'), Timestamp('1991-01-13 00:00:00'), Timestamp('1991-01-19 00:00:00'), Timestamp('1991-01-20 00:00:00'), Timestamp('1991-01-26 00:00:00'), Timestamp('1991-01-27 00:00:00'), Timestamp('1991-02-02 00:00:00'), Timestamp('1991-02-03 00:00:00'), Timestamp('1991-02-09 00:00:00'), Timestamp('1991-02-10 00:00:00'), Timestamp('1991-02-16 00:00:00'), Timestamp('1991-02-17 00:00:00'), Timestamp('1991-02-23 00:00:00'), Timestamp('1991-02-24 00:00:00'), Timestamp('1991-03-02 00:00:00'), Timestamp('1991-03-03 00:00:00'), Timestamp('1991-03-09 00:00:00'), Timestamp('1991-03-10 00:00:00'), Timestamp('1991-03-16 00:00:00'), Timestamp('1991-03-17 00:00:00'), Timestamp('1991-03-23 00:00:00'), Timestamp('1991-03-24 00:00:00'), Timestamp('1991-03-30 00:00:00'), Timestamp('1991-03-31 00:00:00'), Timestamp('1991-04-06 00:00:00'), Timestamp('1991-04-07 00:00:00'), Timestamp('1991-04-13 00:00:00'), Timestamp('1991-04-14 00:00:00'), Timestamp('1991-04-20 00:00:00'), Timestamp('1991-04-21 00:00:00'), Timestamp('1991-04-27 00:00:00'), Timestamp('1991-04-28 00:00:00'), Timestamp('1991-05-04 00:00:00'), Timestamp('1991-05-05 00:00:00'), Timestamp('1991-05-11 00:00:00'), Timestamp('1991-05-12 00:00:00'), Timestamp('1991-05-18 00:00:00'), Timestamp('1991-05-19 00:00:00'), Timestamp('1991-05-25 00:00:00'), Timestamp('1991-05-26 00:00:00'), Timestamp('1991-06-01 00:00:00'), Timestamp('1991-06-02 00:00:00'), Timestamp('1991-06-08 00:00:00'), Timestamp('1991-06-09 00:00:00'), Timestamp('1991-06-15 00:00:00'), Timestamp('1991-06-16 00:00:00'), Timestamp('1991-06-22 00:00:00'), Timestamp('1991-06-23 00:00:00'), Timestamp('1991-06-29 00:00:00'), Timestamp('1991-06-30 00:00:00'), Timestamp('1991-07-06 00:00:00'), Timestamp('1991-07-07 00:00:00'), Timestamp('1991-07-13 00:00:00'), Timestamp('1991-07-14 00:00:00'), Timestamp('1991-07-20 00:00:00'), Timestamp('1991-07-21 00:00:00'), Timestamp('1991-07-27 00:00:00'), Timestamp('1991-07-28 00:00:00'), Timestamp('1991-08-03 00:00:00'), Timestamp('1991-08-04 00:00:00'), Timestamp('1991-08-10 00:00:00'), Timestamp('1991-08-11 00:00:00'), Timestamp('1991-08-17 00:00:00'), Timestamp('1991-08-18 00:00:00'), Timestamp('1991-08-24 00:00:00'), Timestamp('1991-08-25 00:00:00'), Timestamp('1991-08-31 00:00:00'), Timestamp('1991-09-01 00:00:00'), Timestamp('1991-09-07 00:00:00'), Timestamp('1991-09-08 00:00:00'), Timestamp('1991-09-14 00:00:00'), Timestamp('1991-09-15 00:00:00'), Timestamp('1991-09-21 00:00:00'), Timestamp('1991-09-22 00:00:00'), Timestamp('1991-09-28 00:00:00'), Timestamp('1991-09-29 00:00:00'), Timestamp('1991-10-05 00:00:00'), Timestamp('1991-10-06 00:00:00'), Timestamp('1991-10-12 00:00:00'), Timestamp('1991-10-13 00:00:00'), Timestamp('1991-10-19 00:00:00'), Timestamp('1991-10-20 00:00:00'), Timestamp('1991-10-26 00:00:00'), Timestamp('1991-10-27 00:00:00'), Timestamp('1991-11-02 00:00:00'), Timestamp('1991-11-03 00:00:00'), Timestamp('1991-11-09 00:00:00'), Timestamp('1991-11-10 00:00:00'), Timestamp('1991-11-16 00:00:00'), Timestamp('1991-11-17 00:00:00'), Timestamp('1991-11-23 00:00:00'), Timestamp('1991-11-24 00:00:00'), Timestamp('1991-11-30 00:00:00'), Timestamp('1991-12-01 00:00:00'), Timestamp('1991-12-07 00:00:00'), Timestamp('1991-12-08 00:00:00'), Timestamp('1991-12-14 00:00:00'), Timestamp('1991-12-15 00:00:00'), Timestamp('1991-12-21 00:00:00'), Timestamp('1991-12-22 00:00:00'), Timestamp('1991-12-28 00:00:00'), Timestamp('1991-12-29 00:00:00'), Timestamp('1992-01-04 00:00:00'), Timestamp('1992-01-05 00:00:00'), Timestamp('1992-01-11 00:00:00'), Timestamp('1992-01-12 00:00:00'), Timestamp('1992-01-18 00:00:00'), Timestamp('1992-01-19 00:00:00'), Timestamp('1992-01-25 00:00:00'), Timestamp('1992-01-26 00:00:00'), Timestamp('1992-02-01 00:00:00'), Timestamp('1992-02-02 00:00:00'), Timestamp('1992-02-08 00:00:00'), Timestamp('1992-02-09 00:00:00'), Timestamp('1992-02-15 00:00:00'), Timestamp('1992-02-16 00:00:00'), Timestamp('1992-02-22 00:00:00'), Timestamp('1992-02-23 00:00:00'), Timestamp('1992-02-29 00:00:00'), Timestamp('1992-03-01 00:00:00'), Timestamp('1992-03-07 00:00:00'), Timestamp('1992-03-08 00:00:00'), Timestamp('1992-03-14 00:00:00'), Timestamp('1992-03-15 00:00:00'), Timestamp('1992-03-21 00:00:00'), Timestamp('1992-03-22 00:00:00'), Timestamp('1992-03-28 00:00:00'), Timestamp('1992-03-29 00:00:00'), Timestamp('1992-04-04 00:00:00'), Timestamp('1992-04-05 00:00:00'), Timestamp('1992-04-11 00:00:00'), Timestamp('1992-04-12 00:00:00'), Timestamp('1992-04-18 00:00:00'), Timestamp('1992-04-19 00:00:00'), Timestamp('1992-04-25 00:00:00'), Timestamp('1992-04-26 00:00:00'), Timestamp('1992-05-02 00:00:00'), Timestamp('1992-05-03 00:00:00'), Timestamp('1992-05-09 00:00:00'), Timestamp('1992-05-10 00:00:00'), Timestamp('1992-05-16 00:00:00'), Timestamp('1992-05-17 00:00:00'), Timestamp('1992-05-23 00:00:00'), Timestamp('1992-05-24 00:00:00'), Timestamp('1992-05-30 00:00:00'), Timestamp('1992-05-31 00:00:00'), Timestamp('1992-06-06 00:00:00'), Timestamp('1992-06-07 00:00:00'), Timestamp('1992-06-13 00:00:00'), Timestamp('1992-06-14 00:00:00'), Timestamp('1992-06-20 00:00:00'), Timestamp('1992-06-21 00:00:00'), Timestamp('1992-06-27 00:00:00'), Timestamp('1992-06-28 00:00:00'), Timestamp('1992-07-04 00:00:00'), Timestamp('1992-07-05 00:00:00'), Timestamp('1992-07-11 00:00:00'), Timestamp('1992-07-12 00:00:00'), Timestamp('1992-07-18 00:00:00'), Timestamp('1992-07-19 00:00:00'), Timestamp('1992-07-25 00:00:00'), Timestamp('1992-07-26 00:00:00'), Timestamp('1992-08-01 00:00:00'), Timestamp('1992-08-02 00:00:00'), Timestamp('1992-08-08 00:00:00'), Timestamp('1992-08-09 00:00:00'), Timestamp('1992-08-15 00:00:00'), Timestamp('1992-08-16 00:00:00'), Timestamp('1992-08-22 00:00:00'), Timestamp('1992-08-23 00:00:00'), Timestamp('1992-08-29 00:00:00'), Timestamp('1992-08-30 00:00:00'), Timestamp('1992-09-05 00:00:00'), Timestamp('1992-09-06 00:00:00'), Timestamp('1992-09-12 00:00:00'), Timestamp('1992-09-13 00:00:00'), Timestamp('1992-09-19 00:00:00'), Timestamp('1992-09-20 00:00:00'), Timestamp('1992-09-26 00:00:00'), Timestamp('1992-09-27 00:00:00'), Timestamp('1992-10-03 00:00:00'), Timestamp('1992-10-04 00:00:00'), Timestamp('1992-10-10 00:00:00'), Timestamp('1992-10-11 00:00:00'), Timestamp('1992-10-17 00:00:00'), Timestamp('1992-10-18 00:00:00'), Timestamp('1992-10-24 00:00:00'), Timestamp('1992-10-25 00:00:00'), Timestamp('1992-10-31 00:00:00'), Timestamp('1992-11-01 00:00:00'), Timestamp('1992-11-07 00:00:00'), Timestamp('1992-11-08 00:00:00'), Timestamp('1992-11-14 00:00:00'), Timestamp('1992-11-15 00:00:00'), Timestamp('1992-11-21 00:00:00'), Timestamp('1992-11-22 00:00:00'), Timestamp('1992-11-28 00:00:00'), Timestamp('1992-11-29 00:00:00'), Timestamp('1992-12-05 00:00:00'), Timestamp('1992-12-06 00:00:00'), Timestamp('1992-12-12 00:00:00'), Timestamp('1992-12-13 00:00:00'), Timestamp('1992-12-19 00:00:00'), Timestamp('1992-12-20 00:00:00'), Timestamp('1992-12-26 00:00:00'), Timestamp('1992-12-27 00:00:00'), Timestamp('1993-01-02 00:00:00'), Timestamp('1993-01-03 00:00:00'), Timestamp('1993-01-09 00:00:00'), Timestamp('1993-01-10 00:00:00'), Timestamp('1993-01-16 00:00:00'), Timestamp('1993-01-17 00:00:00'), Timestamp('1993-01-23 00:00:00'), Timestamp('1993-01-24 00:00:00'), Timestamp('1993-01-30 00:00:00'), Timestamp('1993-01-31 00:00:00'), Timestamp('1993-02-06 00:00:00'), Timestamp('1993-02-07 00:00:00'), Timestamp('1993-02-13 00:00:00'), Timestamp('1993-02-14 00:00:00'), Timestamp('1993-02-20 00:00:00'), Timestamp('1993-02-21 00:00:00'), Timestamp('1993-02-27 00:00:00'), Timestamp('1993-02-28 00:00:00'), Timestamp('1993-03-06 00:00:00'), Timestamp('1993-03-07 00:00:00'), Timestamp('1993-03-13 00:00:00'), Timestamp('1993-03-14 00:00:00'), Timestamp('1993-03-20 00:00:00'), Timestamp('1993-03-21 00:00:00'), Timestamp('1993-03-27 00:00:00'), Timestamp('1993-03-28 00:00:00'), Timestamp('1993-04-03 00:00:00'), Timestamp('1993-04-04 00:00:00'), Timestamp('1993-04-10 00:00:00'), Timestamp('1993-04-11 00:00:00'), Timestamp('1993-04-17 00:00:00'), Timestamp('1993-04-18 00:00:00'), Timestamp('1993-04-24 00:00:00'), Timestamp('1993-04-25 00:00:00'), Timestamp('1993-05-01 00:00:00'), Timestamp('1993-05-02 00:00:00'), Timestamp('1993-05-08 00:00:00'), Timestamp('1993-05-09 00:00:00'), Timestamp('1993-05-15 00:00:00'), Timestamp('1993-05-16 00:00:00'), Timestamp('1993-05-22 00:00:00'), Timestamp('1993-05-23 00:00:00'), Timestamp('1993-05-29 00:00:00'), Timestamp('1993-05-30 00:00:00'), Timestamp('1993-06-05 00:00:00'), Timestamp('1993-06-06 00:00:00'), Timestamp('1993-06-12 00:00:00'), Timestamp('1993-06-13 00:00:00'), Timestamp('1993-06-19 00:00:00'), Timestamp('1993-06-20 00:00:00'), Timestamp('1993-06-26 00:00:00'), Timestamp('1993-06-27 00:00:00'), Timestamp('1993-07-03 00:00:00'), Timestamp('1993-07-04 00:00:00'), Timestamp('1993-07-10 00:00:00'), Timestamp('1993-07-11 00:00:00'), Timestamp('1993-07-17 00:00:00'), Timestamp('1993-07-18 00:00:00'), Timestamp('1993-07-24 00:00:00'), Timestamp('1993-07-25 00:00:00'), Timestamp('1993-07-31 00:00:00'), Timestamp('1993-08-01 00:00:00'), Timestamp('1993-08-07 00:00:00'), Timestamp('1993-08-08 00:00:00'), Timestamp('1993-08-14 00:00:00'), Timestamp('1993-08-15 00:00:00'), Timestamp('1993-08-21 00:00:00'), Timestamp('1993-08-22 00:00:00'), Timestamp('1993-08-28 00:00:00'), Timestamp('1993-08-29 00:00:00'), Timestamp('1993-09-04 00:00:00'), Timestamp('1993-09-05 00:00:00'), Timestamp('1993-09-11 00:00:00'), Timestamp('1993-09-12 00:00:00'), Timestamp('1993-09-18 00:00:00'), Timestamp('1993-09-19 00:00:00'), Timestamp('1993-09-25 00:00:00'), Timestamp('1993-09-26 00:00:00'), Timestamp('1993-10-02 00:00:00'), Timestamp('1993-10-03 00:00:00'), Timestamp('1993-10-09 00:00:00'), Timestamp('1993-10-10 00:00:00'), Timestamp('1993-10-16 00:00:00'), Timestamp('1993-10-17 00:00:00'), Timestamp('1993-10-23 00:00:00'), Timestamp('1993-10-24 00:00:00'), Timestamp('1993-10-30 00:00:00'), Timestamp('1993-10-31 00:00:00'), Timestamp('1993-11-06 00:00:00'), Timestamp('1993-11-07 00:00:00'), Timestamp('1993-11-13 00:00:00'), Timestamp('1993-11-14 00:00:00'), Timestamp('1993-11-20 00:00:00'), Timestamp('1993-11-21 00:00:00'), Timestamp('1993-11-27 00:00:00'), Timestamp('1993-11-28 00:00:00'), Timestamp('1993-12-04 00:00:00'), Timestamp('1993-12-05 00:00:00'), Timestamp('1993-12-11 00:00:00'), Timestamp('1993-12-12 00:00:00'), Timestamp('1993-12-18 00:00:00'), Timestamp('1993-12-19 00:00:00'), Timestamp('1993-12-25 00:00:00'), Timestamp('1993-12-26 00:00:00'), Timestamp('1994-01-01 00:00:00'), Timestamp('1994-01-02 00:00:00'), Timestamp('1994-01-08 00:00:00'), Timestamp('1994-01-09 00:00:00'), Timestamp('1994-01-15 00:00:00'), Timestamp('1994-01-16 00:00:00'), Timestamp('1994-01-22 00:00:00'), Timestamp('1994-01-23 00:00:00'), Timestamp('1994-01-29 00:00:00'), Timestamp('1994-01-30 00:00:00'), Timestamp('1994-02-05 00:00:00'), Timestamp('1994-02-06 00:00:00'), Timestamp('1994-02-12 00:00:00'), Timestamp('1994-02-13 00:00:00'), Timestamp('1994-02-19 00:00:00'), Timestamp('1994-02-20 00:00:00'), Timestamp('1994-02-26 00:00:00'), Timestamp('1994-02-27 00:00:00'), Timestamp('1994-03-05 00:00:00'), Timestamp('1994-03-06 00:00:00'), Timestamp('1994-03-12 00:00:00'), Timestamp('1994-03-13 00:00:00'), Timestamp('1994-03-19 00:00:00'), Timestamp('1994-03-20 00:00:00'), Timestamp('1994-03-26 00:00:00'), Timestamp('1994-03-27 00:00:00'), Timestamp('1994-04-02 00:00:00'), Timestamp('1994-04-03 00:00:00'), Timestamp('1994-04-09 00:00:00'), Timestamp('1994-04-10 00:00:00'), Timestamp('1994-04-16 00:00:00'), Timestamp('1994-04-17 00:00:00'), Timestamp('1994-04-23 00:00:00'), Timestamp('1994-04-24 00:00:00'), Timestamp('1994-04-30 00:00:00'), Timestamp('1994-05-01 00:00:00'), Timestamp('1994-05-07 00:00:00'), Timestamp('1994-05-08 00:00:00'), Timestamp('1994-05-14 00:00:00'), Timestamp('1994-05-15 00:00:00'), Timestamp('1994-05-21 00:00:00'), Timestamp('1994-05-22 00:00:00'), Timestamp('1994-05-28 00:00:00'), Timestamp('1994-05-29 00:00:00'), Timestamp('1994-06-04 00:00:00'), Timestamp('1994-06-05 00:00:00'), Timestamp('1994-06-11 00:00:00'), Timestamp('1994-06-12 00:00:00'), Timestamp('1994-06-18 00:00:00'), Timestamp('1994-06-19 00:00:00'), Timestamp('1994-06-25 00:00:00'), Timestamp('1994-06-26 00:00:00'), Timestamp('1994-07-02 00:00:00'), Timestamp('1994-07-03 00:00:00'), Timestamp('1994-07-09 00:00:00'), Timestamp('1994-07-10 00:00:00'), Timestamp('1994-07-16 00:00:00'), Timestamp('1994-07-17 00:00:00'), Timestamp('1994-07-23 00:00:00'), Timestamp('1994-07-24 00:00:00'), Timestamp('1994-07-30 00:00:00'), Timestamp('1994-07-31 00:00:00'), Timestamp('1994-08-06 00:00:00'), Timestamp('1994-08-07 00:00:00'), Timestamp('1994-08-13 00:00:00'), Timestamp('1994-08-14 00:00:00'), Timestamp('1994-08-20 00:00:00'), Timestamp('1994-08-21 00:00:00'), Timestamp('1994-08-27 00:00:00'), Timestamp('1994-08-28 00:00:00'), Timestamp('1994-09-03 00:00:00'), Timestamp('1994-09-04 00:00:00'), Timestamp('1994-09-10 00:00:00'), Timestamp('1994-09-11 00:00:00'), Timestamp('1994-09-17 00:00:00'), Timestamp('1994-09-18 00:00:00'), Timestamp('1994-09-24 00:00:00'), Timestamp('1994-09-25 00:00:00'), Timestamp('1994-10-01 00:00:00'), Timestamp('1994-10-02 00:00:00'), Timestamp('1994-10-08 00:00:00'), Timestamp('1994-10-09 00:00:00'), Timestamp('1994-10-15 00:00:00'), Timestamp('1994-10-16 00:00:00'), Timestamp('1994-10-22 00:00:00'), Timestamp('1994-10-23 00:00:00'), Timestamp('1994-10-29 00:00:00'), Timestamp('1994-10-30 00:00:00'), Timestamp('1994-11-05 00:00:00'), Timestamp('1994-11-06 00:00:00'), Timestamp('1994-11-12 00:00:00'), Timestamp('1994-11-13 00:00:00'), Timestamp('1994-11-19 00:00:00'), Timestamp('1994-11-20 00:00:00'), Timestamp('1994-11-26 00:00:00'), Timestamp('1994-11-27 00:00:00'), Timestamp('1994-12-03 00:00:00'), Timestamp('1994-12-04 00:00:00'), Timestamp('1994-12-10 00:00:00'), Timestamp('1994-12-11 00:00:00'), Timestamp('1994-12-17 00:00:00'), Timestamp('1994-12-18 00:00:00'), Timestamp('1994-12-24 00:00:00'), Timestamp('1994-12-25 00:00:00'), Timestamp('1994-12-31 00:00:00'), Timestamp('1995-01-01 00:00:00'), Timestamp('1995-01-07 00:00:00'), Timestamp('1995-01-08 00:00:00'), Timestamp('1995-01-14 00:00:00'), Timestamp('1995-01-15 00:00:00'), Timestamp('1995-01-21 00:00:00'), Timestamp('1995-01-22 00:00:00'), Timestamp('1995-01-28 00:00:00'), Timestamp('1995-01-29 00:00:00'), Timestamp('1995-02-04 00:00:00'), Timestamp('1995-02-05 00:00:00'), Timestamp('1995-02-11 00:00:00'), Timestamp('1995-02-12 00:00:00'), Timestamp('1995-02-18 00:00:00'), Timestamp('1995-02-19 00:00:00'), Timestamp('1995-02-25 00:00:00'), Timestamp('1995-02-26 00:00:00'), Timestamp('1995-03-04 00:00:00'), Timestamp('1995-03-05 00:00:00'), Timestamp('1995-03-11 00:00:00'), Timestamp('1995-03-12 00:00:00'), Timestamp('1995-03-18 00:00:00'), Timestamp('1995-03-19 00:00:00'), Timestamp('1995-03-25 00:00:00'), Timestamp('1995-03-26 00:00:00'), Timestamp('1995-04-01 00:00:00'), Timestamp('1995-04-02 00:00:00'), Timestamp('1995-04-08 00:00:00'), Timestamp('1995-04-09 00:00:00'), Timestamp('1995-04-15 00:00:00'), Timestamp('1995-04-16 00:00:00'), Timestamp('1995-04-22 00:00:00'), Timestamp('1995-04-23 00:00:00'), Timestamp('1995-04-29 00:00:00'), Timestamp('1995-04-30 00:00:00'), Timestamp('1995-05-06 00:00:00'), Timestamp('1995-05-07 00:00:00'), Timestamp('1995-05-13 00:00:00'), Timestamp('1995-05-14 00:00:00'), Timestamp('1995-05-20 00:00:00'), Timestamp('1995-05-21 00:00:00'), Timestamp('1995-05-27 00:00:00'), Timestamp('1995-05-28 00:00:00'), Timestamp('1995-06-03 00:00:00'), Timestamp('1995-06-04 00:00:00'), Timestamp('1995-06-10 00:00:00'), Timestamp('1995-06-11 00:00:00'), Timestamp('1995-06-17 00:00:00'), Timestamp('1995-06-18 00:00:00'), Timestamp('1995-06-24 00:00:00'), Timestamp('1995-06-25 00:00:00'), Timestamp('1995-07-01 00:00:00'), Timestamp('1995-07-02 00:00:00'), Timestamp('1995-07-08 00:00:00'), Timestamp('1995-07-09 00:00:00'), Timestamp('1995-07-15 00:00:00'), Timestamp('1995-07-16 00:00:00'), Timestamp('1995-07-22 00:00:00'), Timestamp('1995-07-23 00:00:00'), Timestamp('1995-07-29 00:00:00'), Timestamp('1995-07-30 00:00:00'), Timestamp('1995-08-05 00:00:00'), Timestamp('1995-08-06 00:00:00'), Timestamp('1995-08-12 00:00:00'), Timestamp('1995-08-13 00:00:00'), Timestamp('1995-08-19 00:00:00'), Timestamp('1995-08-20 00:00:00